# Generated by Django 4.1.3 on 2022-11-17 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', 'create_listitem_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='owner_id',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='listitem',
            old_name='board_id',
            new_name='board',
        ),
    ]
