# Generated by Django 4.1.3 on 2022-11-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_rename_owner_id_board_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='order',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=16),
        ),
    ]
