# Generated by Django 4.1.3 on 2022-11-19 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_alter_listitem_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField(default='')),
                ('order', models.DecimalField(decimal_places=8, default=0.0, max_digits=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.listitem')),
            ],
        ),
    ]
