# Generated by Django 4.1.3 on 2022-11-30 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_alter_carditem_desc_alter_carditem_listitem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carditem',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='listitem',
            options={'ordering': ['order']},
        ),
    ]
