# Generated by Django 4.1.3 on 2022-12-14 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_cardcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardcomment',
            old_name='carditems',
            new_name='carditem',
        ),
    ]
